//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlnciudad
    {
        public int hlnciudadid { get; set; }
        public int hlndepartamentoid { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public Nullable<int> codigopost { get; set; }
    
        public virtual hlndepartamento hlndepartamento { get; set; }
    }
}
