//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlnclase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hlnclase()
        {
            this.hlnvideoclase = new HashSet<hlnvideoclase>();
        }
    
        public int hlnclaseid { get; set; }
        public System.TimeSpan horaini { get; set; }
        public System.TimeSpan horafin { get; set; }
        public sbyte canthoras { get; set; }
        public Nullable<sbyte> calificacion { get; set; }
        public int hlnprogtemaid { get; set; }
        public System.DateTime fecha { get; set; }
        public int hlnusuarioid { get; set; }
        public int profesorid { get; set; }
        public decimal precio { get; set; }
    
        public virtual hlnusuario hlnusuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hlnvideoclase> hlnvideoclase { get; set; }
        public virtual hlnprogtema hlnprogtema { get; set; }
    }
}
