//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlnprogtema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hlnprogtema()
        {
            this.hlnclase = new HashSet<hlnclase>();
        }
    
        public int hlnprogtemaid { get; set; }
        public int hlntemaid { get; set; }
        public System.TimeSpan horaini { get; set; }
        public Nullable<System.TimeSpan> horafin { get; set; }
        public Nullable<decimal> canthoras { get; set; }
        public int hlnprofesorid { get; set; }
        public Nullable<bool> pago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hlnclase> hlnclase { get; set; }
        public virtual hlnusuario hlnusuario { get; set; }
        public virtual hlntema hlntema { get; set; }
    }
}
