//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlntema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hlntema()
        {
            this.hlnprogtema = new HashSet<hlnprogtema>();
        }
    
        public int hlntemaid { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public sbyte hlnmateriaid { get; set; }
        public decimal preciohora { get; set; }
    
        public virtual hlnmateria hlnmateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hlnprogtema> hlnprogtema { get; set; }
    }
}
