//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlntema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hlntema()
        {
            this.hlnprogtema = new HashSet<hlnprogtema>();
        }
    
        public int hlntemaid { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public sbyte hlnmateriaid { get; set; }
        public decimal preciohora { get; set; }
    
        public virtual hlnmateria hlnmateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hlnprogtema> hlnprogtema { get; set; }
    }
}
