//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallearn.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_HallearnEntities : DbContext
    {
        public db_HallearnEntities()
            : base("name=db_HallearnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hlnciudad> hlnciudad { get; set; }
        public virtual DbSet<hlnclase> hlnclase { get; set; }
        public virtual DbSet<hlnconfig> hlnconfig { get; set; }
        public virtual DbSet<hlndepartamento> hlndepartamento { get; set; }
        public virtual DbSet<hlnmateria> hlnmateria { get; set; }
        public virtual DbSet<hlnpais> hlnpais { get; set; }
        public virtual DbSet<hlntema> hlntema { get; set; }
        public virtual DbSet<hlnusuario> hlnusuario { get; set; }
        public virtual DbSet<hlnvideoclase> hlnvideoclase { get; set; }
        public virtual DbSet<hlnprogtema> hlnprogtema { get; set; }
    }
}
